#!/usr/bin/env python

from waflib import Logs


def configure(conf):
	libuade_found = conf.check_cfg(package = 'libuade', uselib_store = 'UADE', args = '--cflags --libs', mandatory = 0)
	libbencodetools_found = conf.check_cc(lib = 'bencodetools', uselib_store = 'UADE', mandatory = 0)
	if libuade_found and libbencodetools_found:
		conf.env['UADE_ENABLED'] = 1
		conf.env['ENABLED_PLUGINS'] += ['uade']
	elif (not libuade_found) and (not libbencodetools_found):
		conf.env['DISABLED_PLUGINS']['uade'] = 'libuade and libbencodetools missing'
	elif not libuade_found:
		conf.env['DISABLED_PLUGINS']['uade'] = 'libuade missing'
	elif not libbencodetools_found:
		conf.env['DISABLED_PLUGINS']['uade'] = 'libbencodetools missing'


def build(bld):
	if not bld.env['UADE_ENABLED']:
		return
	bld(
		features = ['c', 'cshlib'],
		includes = ['../..', '../../gst-libs', '.'],
		uselib = 'GSTREAMER GSTREAMER_BASE GSTREAMER_AUDIO UADE',
		use = 'gstnonstreamaudio',
		target = 'gstuade',
		source = ['gstuade.c', 'gstuaderawdec.c'],
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

