#!/usr/bin/env python

from waflib import Logs


def configure(conf):
	conf.env['DEFINES_DUMB'] = []
	if conf.env['SSE_SUPPORTED']:
		conf.env['DEFINES_DUMB'] += ['_USE_SSE']
	if conf.env['WITH_ALLOCA']:
		conf.env['DEFINES_DUMB'] += ['HAVE_ALLOCA_H']
		conf.env['BUILD_DUMB'] = 1
		conf.env['ENABLED_PLUGINS'] += ['dumbdec']
	else:
		Logs.pprint('RED', 'alloca.h not found -> cannot build DUMB decoder plugin')
		conf.env['DISABLED_PLUGINS']['dumbdec'] = 'alloca.h not found'
	if conf.options.enable_debug:
		conf.env['DEFINES_DUMB'] += ['DEBUGMODE']


def build(bld):
	if not bld.env['BUILD_DUMB']:
		return
	dumb_source = bld.path.ant_glob('*.c') + bld.path.ant_glob('dumb-kode54-git/dumb/src/**/*.c')
	bld(
		features = ['c', 'cshlib'],
		includes = ['../..', '../../gst-libs', '.', 'dumb-kode54-git/dumb/include'],
		uselib = 'GSTREAMER GSTREAMER_BASE GSTREAMER_AUDIO DUMB',
		use = 'gstnonstreamaudio',
		target = 'gstdumb',
		source = dumb_source,
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

