#!/usr/bin/env python

from waflib import Logs


def configure(conf):
	zlib_found = conf.check_cfg(package = 'zlib', uselib_store = 'ZLIB', args = '--cflags --libs', mandatory = 0)
	if zlib_found:
		conf.env['GUNZIP_ENABLED'] = 1
		conf.env['ENABLED_PLUGINS'] += ['gzip']
	else:
		conf.env['DISABLED_PLUGINS']['gzip'] = 'zlib missing'


def build(bld):
	source = bld.path.ant_glob('*.c')
	bld(
		features = ['c', 'cshlib'],
		includes = ['../..', '.'],
		uselib = 'GSTREAMER GSTREAMER_BASE ZLIB',
		target = 'gstgzip',
		source = source,
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

