#!/usr/bin/env python

from waflib import Logs


def configure(conf):
	pass


def build(bld):
	source = bld.path.ant_glob('*.c')
	bld(
		features = ['c', 'cshlib'],
		includes = ['../..', '.'],
		uselib = 'GSTREAMER GSTREAMER_BASE',
		target = 'gstumxparse',
		source = source,
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

