#!/usr/bin/env python

from waflib import Logs


def configure(conf):
	if conf.check_cc(lib = 'WildMidi', uselib_store = 'WILDMIDI', mandatory = 0) and \
	   conf.check_cc(header_name = 'wildmidi_lib.h', uselib_store = 'WILDMIDI', mandatory = 0):
		conf.env['WILDMIDI_ENABLED'] = 1
		conf.env['ENABLED_PLUGINS'] += ['wildmidi']
	else:
		conf.env['DISABLED_PLUGINS']['wildmidi'] = 'could not find wildmidi library and/or header'


def build(bld):
	if not bld.env['WILDMIDI_ENABLED']:
		return
	bld(
		features = ['c', 'cshlib'],
		includes = ['../..', '../../gst-libs', '.'],
		uselib = 'GSTREAMER GSTREAMER_BASE GSTREAMER_AUDIO WILDMIDI',
		use = 'gstnonstreamaudio',
		target = 'gstwildmidi',
		source = ['gstwildmididec.c', 'plugin.c'],
		defines = ['HAVE_CONFIG_H'],
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

