#!/usr/bin/env python

from waflib import Logs


def configure(conf):
	if conf.check_cfg(package = 'libopenmpt', uselib_store = 'OPENMPT', args = '--cflags --libs', mandatory = 0):
		conf.env['OPENMPT_ENABLED'] = 1
		conf.env['ENABLED_PLUGINS'] += ['openmpt']
	else:
		conf.env['DISABLED_PLUGINS']['openmpt'] = 'could not find libopenmpt'


def build(bld):
	if not bld.env['OPENMPT_ENABLED']:
		return
	bld(
		features = ['c', 'cshlib'],
		includes = ['../..', '../../gst-libs', '.'],
		uselib = 'GSTREAMER GSTREAMER_BASE GSTREAMER_AUDIO OPENMPT',
		use = 'gstnonstreamaudio',
		target = 'gstopenmpt',
		source = ['gstopenmptdec.c', 'plugin.c'],
		defines = ['HAVE_CONFIG_H'],
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

