#!/usr/bin/env python

from waflib import Logs


def configure(conf):
	conf.env['ENABLED_PLUGINS'] += ['umxparse']
	conf.env['UMXPARSE_ENABLED'] = 1


def build(bld):
	if not bld.env['UMXPARSE_ENABLED']:
		return
	source = bld.path.ant_glob('*.c')
	bld(
		features = ['c', 'cshlib'],
		includes = ['../..', '.'],
		uselib = 'GSTREAMER GSTREAMER_BASE',
		target = 'gstumxparse',
		source = source,
		install_path = bld.env['PLUGIN_INSTALL_PATH']
	)

